Repository bear-bear-bear/mogakco, pull requests merged in 2021-07, with the labels that each got.

#198 FEATURE: 채팅방 연결, 일부 이슈 픽스, SWR 설치
  nest/controllers/chat.gateway.ts
  next/components/video-chat/ChatSection/Chat/style.tsx
  next/components/video-chat/ChatSection/ChatList/index.tsx
  next/package-lock.json
  next/package.json
  next/pages/chat/[id].tsx
Labels: backend, feature, frontend

#199 FEATURE: SWR 예시
  next/components/signup/Start/index.tsx
  next/components/video-chat/ChatSection/ChatList/index.tsx
  next/pages/signup.tsx
Labels: frontend

#200 REFACTOR: SWR Hooks 관리
  next/hooks/useSignUp.tsx
  next/pages/signup.tsx
Labels: frontend, refactor

#201 REFACTOR: redux 떨쳐내기 1차
  next/.babelrc
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
  next/components/signup/Start/index.tsx
  next/hooks/useDebugLog.ts
  next/hooks/useLanding.tsx
  next/lib/APIs.ts
  next/lib/apiClient.ts
  next/pages/signup.tsx
  next/redux/reducers/common/user.ts
  next/redux/reducers/signup/index.ts
  next/redux/sagas/common/user.ts
  next/redux/sagas/signup/index.ts
  next/redux/selectors/signup/index.ts
  next/tsconfig.json
  next/typings/auth.ts
Labels: fix, frontend, refactor

#203 REFACTOR: page/signup ReDuX 제거
  next/hooks/useSignUp.tsx
  next/pages/_app.tsx
  next/pages/signup.tsx
Labels: frontend, refactor

#204 FIX: initial error 수정
  next/pages/signup.tsx
Labels: fix, frontend

#205 feature: 유저 상태값 추가
  next/hooks/useSignUp.tsx
Labels: frontend

#206 FIX: Landing Email 폼 반영 되게 끔 수정
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
Labels: fix, frontend

#208 FEATURE: 소켓 커넥션 작성, 프런트엔드 수정
  nest/controllers/chat.gateway.ts
  next/components/video-chat/ChatSection/Chat/Announcement.tsx
  next/components/video-chat/ChatSection/Chat/style.tsx
  next/components/video-chat/ChatSection/InputBox/index.tsx
  next/components/video-chat/ChatSection/InputBox/style.tsx
  next/hooks/useInput.tsx
  next/package-lock.json
  next/package.json
  next/pages/chat/[id].tsx
Labels: backend, frontend

#209 MODIFY: request url changes
  nest/controllers/auth.controller.ts
Labels: backend

#214 FEAT: 로그인 페이지 퍼블리싱 및 기본 기능
  next/components/common/Input/components.tsx
  next/components/common/Input/typings.ts
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
  next/components/landing/Header/index.tsx
  next/components/sign-in/index.tsx
  next/components/sign-up/Start/index.tsx
  next/lib/isAllPropertyTruthy.ts
  next/pages/sign-in.tsx
Labels: feature, frontend

#217 FIX: 기존 오지는 리렌더링이 일어나던 Required 페이지의 성능 대폭 개선
  next/components/sign-up/Required/Sections/ErrorSection.tsx
  next/components/sign-up/Required/Sections/PasswordSection.tsx
  next/components/sign-up/Required/Sections/TermSection.tsx
  next/components/sign-up/Required/Sections/UsernameSection.tsx
  next/components/sign-up/Required/index.tsx
  next/components/sign-up/Required/typings.ts
Labels: fix, frontend, refactor

#218 FEAT: 32px svg 아이콘 20개 추가
  next/public/assets/svg/chart-line-alt1.svg
  next/public/assets/svg/chart-pie-alt.svg
  next/public/assets/svg/check.svg
  next/public/assets/svg/conversation.svg
  next/public/assets/svg/copy.svg
  next/public/assets/svg/cross.svg
  next/public/assets/svg/delete-alt.svg
  next/public/assets/svg/download.svg
  next/public/assets/svg/mic.svg
  next/public/assets/svg/minus.svg
  next/public/assets/svg/notification.svg
  next/public/assets/svg/plus.svg
  next/public/assets/svg/reward.svg
  next/public/assets/svg/rotate-right.svg
  next/public/assets/svg/settings.svg
  next/public/assets/svg/sound-max.svg
  next/public/assets/svg/sound-mute-alt.svg
  next/public/assets/svg/translate.svg
  next/public/assets/svg/upload.svg
  next/public/assets/svg/warning.svg
Labels: frontend

#215 FEATURE: 로그인 처리
  nest/controllers/auth.controller.ts
  nest/main.ts
  next/components/sign-in/index.tsx
  next/lib/apiClient.ts
  next/lib/fetchers.ts
  next/pages/index.tsx
  next/typings/auth.ts
Labels: backend, feature, fix, frontend

#219 MODIFY: 로그인 연장 테스트 개선
  next/pages/index.tsx
Labels: frontend

#220 FEAT: 로그인 연장에 숟가락 얹기
  next/pages/index.tsx
Labels: feature, frontend

#222 FEAT: 대시보드 페이지 생성, 퍼블리싱과 링크 연결 완료
  next/components/dashboard/CardAnchor/index.tsx
  next/components/dashboard/CardAnchor/style.tsx
  next/components/dashboard/Container/index.tsx
  next/components/dashboard/Container/style.tsx
  next/components/globalStyles/media.tsx
  next/components/video-chat/ChatSection/ChatList/index.tsx
  next/components/video-chat/ChatSection/InputBox/index.tsx
  next/pages/dashboard/index.tsx
  next/pages/my-page/index.tsx
  next/pages/sign-in/index.tsx
  next/pages/video-chat/[id].tsx
  next/public/assets/svg/chat-alt5.svg
  next/public/assets/svg/screen-enlarge.svg
  next/public/assets/svg/screen-reduce.svg
  next/public/assets/svg/video-camera.svg
  next/public/assets/svg/video-chat.svg
Labels: feature, frontend

#223 fix: next/Link 관련 심각한 seo 이슈 해결
  next/components/landing/Header/index.tsx
  next/pages/dashboard/index.tsx
Labels: fix, frontend

#224 MODIFY: 로그인 로직 수정 및 메모리 스토어 구현
  nest/.env.example
  nest/controllers/auth.controller.ts
  nest/guard/non-auth.guard.ts
  nest/services/auth.service.ts
  nest/services/passport/jwt.refresh.strategy.ts
  nest/services/passport/jwt.strategy.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  nest/test/e2e/user/mypage.e2e-spec.ts
  next/components/sign-in/index.tsx
  next/lib/apiClient.ts
  next/lib/fetchers.ts
  next/pages/video-chat/[id].tsx
  next/typings/auth.ts
Labels: backend, feature, frontend, refactor, request change, test

#226 REFACTOR: 반복되는 access 재발급 요청 로직 함수화
  next/lib/apiClient.ts
Labels: frontend, refactor, risk

#231 FEATURE: 로그아웃 기능 구현 & 이슈 해결
  nest/controllers/auth.controller.ts
  next/components/landing/Header/AuthButtons.tsx
  next/components/landing/Header/index.tsx
  next/components/video-chat/ChatSection/ChatList/index.tsx
  next/components/video-chat/ChatSection/InputBox/index.tsx
  next/lib/apiClient.ts
  next/lib/fetchers.ts
  next/lib/fromActionTypes.ts
  next/pages/_app.tsx
  next/pages/index.tsx
  next/pages/sign-in/index.tsx
  next/pages/sign-up/index.tsx
  next/pages/video-chat/[id].tsx
Labels: backend, feature, frontend

#225 FEAT: development mode 전용 로그 함수 추가 및 토큰 갱신 인터셉터 리팩토링
  next/components/sign-in/index.tsx
  next/components/sign-up/Start/index.tsx
  next/components/video-chat/ChatSection/InputBox/index.tsx
  next/hooks/useDebugLog.ts
  next/lib/apiClient.ts
  next/lib/devModeLog.ts
  next/lib/fetchers.ts
  next/pages/video-chat/[id].tsx
Labels: frontend, refactor

#227 TEST: 로그인 연장 테스트 버튼에 로딩 추가
  next/components/common/Input/typings.ts
  next/components/sign-up/ProgressBar/style.tsx
  next/lib/apiClient.ts
  next/lib/fetchers.ts
  next/pages/index.tsx
Labels: frontend, test

#228 REFACTOR: 랜딩 페이지에서 회원가입 페이지로 넘어갈 때 이메일을 넘겨주는 방식을 swr에서 next/router로 변경
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
  next/components/sign-up/Start/index.tsx
  next/hooks/useLanding.tsx
Labels: frontend, refactor

#229 STYLE: media screenSizes 객체 이름을 breakpoints 로 변경하기
  next/components/dashboard/Container/style.tsx
  next/components/globalStyles/media.tsx
Labels: frontend, style

#230 FIX: header 로그인 로그아웃 버튼 모바일 화면 크기에서 화면 넘어가는 부분 수정
  next/components/landing/Header/AuthButtons.tsx
  next/components/landing/Header/index.tsx
  next/components/landing/Header/style.tsx
  next/lib/fetchers.ts
Labels: fix, frontend

#235 FIX: #234 해결
  next/components/sign-up/Required/Sections/PasswordSection.tsx
  next/components/sign-up/Required/index.tsx
  next/components/sign-up/Start/index.tsx
Labels: fix, frontend

#237 FIX: 프런트엔드 회원가입 로그인 패스 문제, useEffect storage event 이슈 해결
  nest/services/auth.service.ts
  next/components/landing/Header/AuthButtons.tsx
  next/components/sign-up/Optional/index.tsx
  next/lib/apiClient.ts
  next/lib/fetchers.ts
  next/pages/_app.tsx
Labels: backend, bug, fix, frontend

#240 FIX: 랜딩 이메일 첫 진입 시 포커스 삭제
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
Labels: fix, frontend

#243 STYLE: rename lib/fetchers.ts -> lib/api.ts
  next/components/landing/Header/AuthButtons.tsx
  next/components/sign-in/index.tsx
  next/components/sign-up/Optional/index.tsx
  next/components/sign-up/Start/index.tsx
  next/lib/apiClient.ts
  next/lib/apis.ts
  next/pages/index.tsx
  next/pages/sign-in/index.tsx
  next/pages/sign-up/index.tsx
  next/pages/sign-up/optional.tsx
  next/pages/video-chat/[id].tsx
Labels: frontend, style

#244 FEATURE: sign-out 도 user 추가 및 login, join 에 해시값 삭제
  nest/controllers/auth.controller.ts
  nest/services/auth.service.ts
Labels: backend

#245 STYLE: 타입 네임 컨벤션 수정
  next/components/sign-up/Optional/index.tsx
  next/lib/apis.ts
  next/typings/auth.ts
Labels: frontend, style

#248 FEATURE: 백엔드 유저 로그인 상태 인증 Api 작성
  nest/controllers/auth.controller.ts
  nest/lib/promisifyJwtVerify.ts
  nest/package-lock.json
  nest/package.json
  nest/services/auth.service.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
Labels: backend, feature, test

#247 FIX: Nest 버그 및 소켓 부분 작성
  nest/modules/auth.module.ts
  nest/modules/chat.module.ts
  nest/nest-cli.json
  nest/test/helper/userMockRepository.ts
  nest/tsconfig.build.json
  next/components/video-chat/ChatSection/ChatList/index.tsx
  next/components/video-chat/ChatSection/InputBox/index.tsx
  next/hooks/useSocket.tsx
  next/pages/video-chat/[id].tsx
Labels: backend, fix, frontend

#241 FEAT: 인증 정보에 따른 페이지 접근 제어 작업 - close #210, #212
  nest/controllers/auth.controller.ts
  nest/models/repositories/user.repository.ts
  nest/services/auth.service.ts
  nest/services/user.service.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  next/.eslintrc.js
  next/components/landing/Header/AuthButtons.tsx
  next/components/landing/Header/index.tsx
  next/components/sign-in/index.tsx
  next/components/sign-up/Optional/index.tsx
  next/components/sign-up/Start/index.tsx
  next/components/video-chat/ChatSection/ChatList/index.tsx
  next/hooks/useUser.tsx
  next/lib/apiClient.ts
  next/lib/apis.ts
  next/lib/fetcher.ts
  next/lib/token.ts
  next/pages/_app.tsx
  next/pages/dashboard/index.tsx
  next/pages/index.tsx
  next/pages/my-page/index.tsx
  next/pages/sign-in/index.tsx
  next/pages/sign-up/index.tsx
  next/pages/sign-up/optional.tsx
  next/pages/sign-up/required.tsx
  next/pages/video-chat/[id].tsx
  next/typings/auth.ts
  next/typings/common.ts
Labels: feature, frontend, risk

#249 FEAT: 대쉬보드 페이지 카드에 fade 애니메이션 추가
  next/components/dashboard/CardLink/index.tsx
  next/components/dashboard/CardLink/style.tsx
Labels: feature, frontend

#250 FEAT: 프로덕션 빌드를 위한 스크립트 명령어 추가 및 빌드 과정 에러 제거
  next/components/common/Desc/index.tsx
  next/components/common/Desc/style.tsx
  next/components/common/Label/index.tsx
  next/components/common/Label/style.tsx
  next/components/globalStyles/media.tsx
  next/components/landing/ContentBlock/LeftContentBlock/style.tsx
  next/components/sign-up/Required/Sections/PasswordSection.tsx
  next/lib/apiClient.ts
  next/next.config.js
  next/package.json
  next/test/e2e/integration/landing.test.ts
  next/test/unit/frontend/components/TestRenderer.test.tsx
  next/test/unit/frontend/pages/TestRenderer.spec.tsx
  next/typings/common.ts
Labels: feature, fix, frontend

#251 FEAT: 페이지 최상위 컨테이너를 main으로 변경 (접근성)
  next/components/common/AuthContainer/style.tsx
  next/components/dashboard/Container/style.tsx
  next/components/video-chat/Container/style.tsx
Labels: feature, frontend
