Repository bear-bear-bear/mogakco, pull requests merged in 2021-06, with the labels that each got.

#117 기능: 백엔드 리팩터링 및 모델링 수정
  nest/.eslintrc.json
  nest/models/entities/helper/abstract.ts
  nest/models/entities/user-field.entity.ts
  nest/models/entities/user-verify.entity.ts
  nest/models/entities/user.entity.ts
  nest/models/entities/users-job.entity.ts
Labels: backend, refactor

#119 리팩터링: 테스트 환경 개선과 백엔드 리팩터링
  nest/controllers/auth.controller.ts
  nest/jest.config.e2e.ts
  nest/jest.config.ts
  nest/models/entities/helper/abstract.ts
  nest/models/entities/user-field.entity.ts
  nest/models/repositories/user-verify.repository.ts
  nest/modules/app.module.ts
  nest/modules/auth.module.ts
  nest/modules/user.module.ts
  nest/package.json
  nest/services/auth.service.ts
  nest/services/user.service.ts
  nest/test/e2e/test.e2e-spec.ts
  nest/test/e2e/test.e2e-test.ts
  nest/tsconfig.json
Labels: backend, devops, refactor, test

#121 사용자 회원가입에 인증 검증 로직 추가
  nest/services/auth.service.ts
Labels: backend

#118 feat: 회원가입 잔기능 추가 및 성능 개선
  next/components/common/AuthContainer/index.js
  next/components/common/Button/index.js
  next/components/common/Button/style.js
  next/components/landing/ContentBlock/LeftContentBlock/index.js
  next/components/signup/Auth/index.js
  next/components/signup/Complete/index.js
  next/components/signup/Info/index.js
  next/components/signup/Interest/index.js
  next/lib/apiClient.js
  next/package-lock.json
  next/package.json
  next/pages/signup.js
  next/redux/selectors/landing/index.js
  next/redux/selectors/signup/index.js
Labels: feature, frontend, refactor

#120 백엔드 분야, 직업 목록, 이메일 Api 테스트, 시딩 환경 작성
  .github/workflows/node.js.yml
  nest/.env.example
  nest/controllers/auth.controller.ts
  nest/factory/users-field.factory.ts
  nest/factory/users-job.factory.ts
  nest/package-lock.json
  nest/package.json
  nest/seeders/user-props.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/user/user-props.e2e-spec.ts
  nest/test/type/mock-data-type.ts
Labels: backend, test

#125 feat: Input 컴포넌트 기능 추가 및 구조 정립
  next/components/common/Checkbox/index.js
  next/components/common/Input/CheckboxInput/index.js
  next/components/common/Input/CheckboxInput/style.js
  next/components/common/Input/PasswordInput/index.js
  next/components/common/Input/PasswordInput/style.js
  next/components/common/Input/TextInput/index.js
  next/components/common/Input/TextInput/style.js
  next/components/common/InputBox/index.js
  next/components/common/Label/index.js
  next/components/signup/Auth/index.js
  next/components/signup/Info/index.js
Labels: feature, frontend, style

#126 fix: null 참조 에러 수정
  next/components/signup/Interest/index.js
Labels: fix, frontend

#122 회원가입 정규식 요청 작성 및 검증 로직, 테스트 추가
  nest/controllers/auth.controller.ts
  nest/controllers/dto/response.ts
  nest/models/dto/create-user.dto.ts
  nest/models/entities/user.entity.ts
  nest/models/repositories/user.repository.ts
  nest/services/auth.service.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
  nest/test/e2e/helper/support.ts
Labels: backend, request change, test

#128 fix: username 정규식 수정
  next/lib/regex.js
Labels: fix, frontend

#130 사용자 시딩 추가
  nest/.eslintrc.json
  nest/factory/helper/utils.ts
  nest/factory/users-field.factory.ts
  nest/factory/users-job.factory.ts
  nest/factory/users.factory.ts
  nest/models/entities/user.entity.ts
  nest/models/repositories/user.repository.ts
  nest/package.json
  nest/seeders/user-props.ts
Labels: backend, feature

#127 feat: 회원가입 첫 페이지 UI 변경
  next/components/common/Label/style.js
  next/components/signup/Auth/index.js
  next/components/signup/Auth/style.js
  next/components/signup/common/styles.js
  next/public/assets/png/GitHub-Mark-Light-32px.png
  next/public/assets/svg/btn_google_light_normal_ios.svg
  next/redux/reducers/landing/index.js
Labels: feature, fix, frontend

#135 백엔드 이슈 처리 및 시딩, 테스트 개선
  nest/.env.example
  nest/jest.config.e2e.ts
  nest/lib/test-support.ts
  nest/models/dto/create-user.dto.ts
  nest/models/entities/user.entity.ts
  nest/models/repositories/ user-job.reposity.ts
  nest/models/repositories/user.repository.ts
  nest/modules/auth.module.ts
  nest/package.json
  nest/seeders/user-props.ts
  nest/services/auth.service.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
  nest/test/e2e/helper/support.ts
  nest/test/e2e/test.e2e-spec.ts
Labels: backend, feature, test

#136 feat: 입력값 취소 버튼이 있는 이메일 컴포넌트 추가, 기타 Input 관련 에러 수정
  next/components/common/Button/style.js
  next/components/common/Input/EmailInput/index.js
  next/components/common/Input/EmailInput/style.js
  next/components/common/Input/TextInput/index.js
  next/components/common/Input/TextInput/style.js
  next/components/landing/ContentBlock/LeftContentBlock/index.js
  next/components/landing/ContentBlock/LeftContentBlock/style.js
  next/components/signup/Auth/index.js
Labels: feature, fix, frontend

#141 백엔드 이슈사항 처리 ( 회원가입 및 회원가입 데이터 )
  nest/.env.example
  nest/controllers/auth.controller.ts
  nest/controllers/pipe/parse-join-pipe.ts
  nest/models/dto/create-user.dto.ts
  nest/modules/auth.module.ts
  nest/services/auth.service.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
Labels: fix, request change, test

#140 JWT AccessToken with RefreshToken 로그인 기능
  nest/.env.example
  nest/controllers/auth.controller.ts
  nest/controllers/type/guard-type.ts
  nest/guard/jwt-auth.guard.ts
  nest/guard/non-auth.guard.ts
  nest/models/dto/login-user.dto.ts
  nest/models/entities/user.entity.ts
  nest/modules/auth.module.ts
  nest/services/auth.service.ts
  nest/services/passport/jwt.payload.ts
  nest/services/passport/jwt.refresh.strategy.ts
  nest/services/passport/jwt.strategy.ts
  nest/services/passport/local.strategy.ts
  nest/services/type/auth.ts
Labels: backend, feature

#146 feature: 백엔드 jwt 로그인 기능 준비를 위한 서비스 로직 추가, 가드 로직 작성
  nest/controllers/auth.controller.ts
  nest/guard/jwt-auth.guard.ts
  nest/main.ts
  nest/modules/app.module.ts
  nest/services/passport/jwt.guard.ts
  nest/services/passport/jwt.refresh.strategy.ts
  nest/services/passport/jwt.strategy.ts
  nest/services/passport/local-auth.guard.ts
  nest/services/type/auth.ts
Labels: backend, feature

#147 feature: JWT 로그인 1차 완성
  nest/controllers/auth.controller.ts
  nest/controllers/pipe/parse-join-pipe.ts
  nest/lib/test-support.ts
  nest/models/dto/create-user.dto.ts
  nest/models/dto/login-user.dto.ts
  nest/models/entities/user.entity.ts
  nest/models/entities/users-job.entity.ts
  nest/models/repositories/ user-job.reposity.ts
  nest/models/repositories/user-field.repository.ts
  nest/models/repositories/user.repository.ts
  nest/services/auth.service.ts
  nest/services/passport/jwt.refresh.strategy.ts
  nest/services/user.service.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
Labels: backend, feature

#150 TEST: 백엔드 로그인 테스트 작성
  nest/modules/app.module.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  nest/test/e2e/helper/support.ts
Labels: backend, test

#153 FEATURE: 백엔드 타입 분리 및 프런트엔드 환경 포트 추가
  nest/.env.example
  nest/guard/jwt-auth.guard.ts
  nest/jest.config.e2e.ts
  nest/jest.config.ts
  nest/modules/app.module.ts
  nest/tsconfig.json
  nest/typing/auth.ts
  nest/typing/common.ts
  nest/typing/example.ts
Labels: backend, refactor

#154 FEATURE: 백엔드 타입 분리 적용
  nest/controllers/auth.controller.ts
  nest/controllers/pipe/parse-join-pipe.ts
  nest/controllers/type/get-user-type.ts
  nest/controllers/type/guard-type.ts
  nest/guard/non-auth.guard.ts
  nest/models/dto/create-user.dto.ts
  nest/models/dto/login-user.dto.ts
  nest/models/repositories/user.repository.ts
  nest/services/auth.service.ts
  nest/services/email.service.ts
  nest/services/passport/jwt.refresh.strategy.ts
  nest/services/passport/jwt.strategy.ts
  nest/services/type/auth.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
Labels: backend

#158 TEST: 프런트엔드 E2E 환경 Cypress 설치 및 테스팅 작성
  next/components/landing/Footer/index.tsx
  next/cypress.json
  next/cypress/integration/landing.ts
  next/cypress/tsconfig.json
  next/package-lock.json
  next/package.json
Labels: feature, frontend, test

#160 TEST: 프런트엔드 스토리북 추가
  next/.storybook/main.js
  next/.storybook/preview.js
  next/stories/Button.stories.tsx
  next/stories/Button.tsx
  next/stories/Header.stories.tsx
  next/stories/Header.tsx
  next/stories/Introduction.stories.mdx
  next/stories/Page.stories.tsx
  next/stories/Page.tsx
  next/stories/assets/code-brackets.svg
  next/stories/assets/colors.svg
  next/stories/assets/comments.svg
  next/stories/assets/direction.svg
  next/stories/assets/flow.svg
  next/stories/assets/plugin.svg
  next/stories/assets/repo.svg
  next/stories/assets/stackalt.svg
  next/stories/button.css
  next/stories/header.css
  next/stories/page.css
Labels: feature, frontend, test

#162 REFACTOR: 백엔드 코드 전반 리팩터링
  nest/controllers/auth.controller.ts
  nest/controllers/exception/login.exception.ts
  nest/controllers/user.controller.ts
  nest/models/repositories/user-verify.repository.ts
  nest/modules/user.module.ts
  nest/services/auth.service.ts
  nest/services/email.service.ts
  nest/services/user.service.ts
Labels: backend, fix, refactor

#164 FEATURE: Select 공용 컴포넌트 1차 작성
  next/.storybook/main.js
  next/components/common/Select/Select.stories.tsx
  next/components/common/Select/index.tsx
  next/components/signup/OptionalInfo/index.tsx
  next/package-lock.json
  next/package.json
Labels: feature, frontend, refactor

#165 REFACTOR: 회원가입 >OptionalInfo 페이지 리팩터링
  next/.eslintrc.js
  next/components/common/Desc/index.tsx
  next/components/common/Label/index.tsx
  next/components/common/Label/style.tsx
  next/components/common/Select/index.tsx
  next/components/signup/OptionalInfo/index.tsx
  next/hooks/useTypedDispatch.ts
  next/hooks/useTypedSelector.ts
  next/package-lock.json
  next/package.json
  next/pages/signup.tsx
  next/redux/reducers/common/user.ts
  next/redux/reducers/signup/index.ts
  next/redux/sagas/signup/index.ts
  next/redux/selectors/signup/index.ts
  next/redux/store/configureStore.ts
  next/typings/auth.ts
Labels: frontend, refactor

#168 REFACTOR: signup redux, start page 타입스크립트 작업 및 리팩터링
  next/components/common/Input/EmailInput/index.tsx
  next/components/signup/Start/index.tsx
  next/components/signup/Start/useEffectSignUpStart.tsx
  next/hooks/useInput.tsx
  next/lib/APIs.ts
  next/lib/apiClient.ts
  next/redux/reducers/signup/index.ts
  next/redux/sagas/signup/index.ts
  next/typings/auth.ts
  next/typings/common.ts
Labels: frontend, refactor

#169 REFACTOR: redux/ 타입 정상화
  next/redux/reducers/common/user.ts
  next/redux/reducers/landing/index.ts
  next/redux/reducers/signup/index.ts
  next/redux/sagas/common/user.ts
  next/redux/sagas/signup/index.ts
  next/redux/selectors/common/user.ts
  next/typings/auth.ts
  next/typings/common.ts
Labels: fix, frontend, refactor

#173 REFACTOR: 프런트엔드 타입 분할 작업 1차 [galaxy4276]
  next/components/common/AuthContainer/index.tsx
  next/components/common/Button/index.tsx
  next/components/common/Button/style.tsx
  next/components/common/CustomHead/index.tsx
  next/components/common/Form/index.tsx
  next/components/common/InputWrapper/index.tsx
  next/components/common/ScrollTop/index.tsx
  next/components/common/Select/index.tsx
  next/components/common/Warning/index.tsx
  next/lib/APIs.ts
  next/lib/fromActionTypes.ts
  next/redux/reducers/signup/index.ts
  next/redux/sagas/signup/index.ts
  next/tsconfig.json
  next/typings/auth.ts
Labels: frontend, refactor

#174 refactor: 타입스크립트 정상화 작업 components/ 1차
  next/components/globalStyles/_FontFace.tsx
  next/components/globalStyles/index.tsx
  next/components/globalStyles/media.tsx
  next/components/landing/Container/index.tsx
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
  next/components/landing/ContentBlock/LeftContentBlock/style.tsx
  next/components/landing/ContentBlock/RightContentBlock/index.tsx
  next/components/landing/ContentBlock/index.tsx
  next/components/landing/Header/index.tsx
  next/components/landing/Header/style.tsx
  next/components/landing/MiddleBlock/index.tsx
  next/components/signup/End/index.tsx
  next/components/signup/End/style.tsx
  next/custom.d.ts
  next/pages/index.tsx
  next/tsconfig.json
Labels: fix, frontend, refactor

#175 FIX: 기존 html에 있는 size prop를 커스텀 prop name으로 사용하여 생기던 문제 수정 - close #172 [bear-bear-bear]
  next/components/common/Button/index.tsx
  next/components/common/Button/style.tsx
  next/components/common/Desc/index.tsx
  next/components/common/Desc/style.tsx
  next/components/common/Input/EmailInput/index.tsx
  next/components/common/Input/PasswordInput/index.tsx
  next/components/common/Input/TextInput/index.tsx
  next/components/common/Input/TextInput/style.tsx
  next/components/common/Label/index.tsx
  next/components/common/Label/style.tsx
  next/components/signup/RequiredInfo/index.tsx
  next/components/signup/Start/index.tsx
  next/stories/Button.stories.tsx
  next/stories/Button.tsx
  next/stories/Header.tsx
Labels: fix, frontend

#177 FEATURE: 프런트엔드 Path Alias 수정 및 추가
  next/.babelrc
  next/components/landing/Header/style.tsx
  next/next.config.js
  next/tsconfig.json
Labels: feature, frontend

#179 Input 컴포넌트 통합 - close #171
  next/components/common/Input/CheckboxInput/index.tsx
  next/components/common/Input/CheckboxInput/style.tsx
  next/components/common/Input/EmailInput/index.tsx
  next/components/common/Input/EmailInput/style.tsx
  next/components/common/Input/PasswordInput/index.tsx
  next/components/common/Input/PasswordInput/style.tsx
  next/components/common/Input/TextInput/index.tsx
  next/components/common/Input/TextInput/style.tsx
  next/components/common/Input/components.tsx
  next/components/common/Input/index.tsx
  next/components/common/Input/style.tsx
  next/components/common/Input/typings.ts
  next/components/common/Label/index.tsx
  next/components/landing/ContentBlock/LeftContentBlock/style.tsx
  next/components/signup/RequiredInfo/index.tsx
  next/components/signup/Start/index.tsx
Labels: frontend, refactor

#178 REFACTOR: 회원가입 > Start 페이지 리팩터링
  next/components/common/Button/index.tsx
  next/components/common/Button/style.tsx
  next/components/common/Input/components.tsx
  next/components/common/Input/typings.ts
  next/components/signup/Start/index.tsx
  next/components/signup/Start/useEffectSignUpStart.tsx
  next/redux/reducers/landing/index.ts
  next/tsconfig.json
  next/typings/auth.ts
  next/typings/custom.d.ts
  next/typings/emotion.d.ts
Labels: frontend, refactor

#182 MODIFY: Cypress 테스트 디렉터리 수정
  next/cypress.json
  next/package.json
  next/test/e2e/cypress/tsconfig.json
  next/test/e2e/integration/landing.ts
Labels: frontend, test

#181 fix: 사용하지 않는 모듈 삭제
  next/components/common/Input/typings.ts
Labels: fix

#176 REFACTOR: 회원가입 > RequiredInfo 리팩터링 양도 -> bear-bear-bear
  next/components/common/Input/typings.ts
  next/components/signup/End/index.tsx
  next/components/signup/OptionalInfo/index.tsx
  next/components/signup/RequiredInfo/Sections/ErrorSection.tsx
  next/components/signup/RequiredInfo/Sections/PasswordSection.tsx
  next/components/signup/RequiredInfo/Sections/TermSection.tsx
  next/components/signup/RequiredInfo/Sections/UsernameSection.tsx
  next/components/signup/RequiredInfo/index.tsx
  next/components/signup/RequiredInfo/typings.ts
  next/components/signup/common/styles.tsx
  next/lib/isAllPropertyTruthy.ts
  next/package-lock.json
Labels: frontend, help wanted, refactor

#184 refactor: 페이지 진입 시 주던 focus효과를 useEffect -> useLayoutEffect로 변경
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
  next/components/signup/End/index.tsx
  next/components/signup/Start/index.tsx
Labels: feature, refactor

#185 FEATURE: 백엔드 / 프런트엔드 유지 보수 및 보안 기능 추가
  nest/main.ts
  nest/package-lock.json
  nest/package.json
  next/components/signup/OptionalInfo/index.tsx
  next/redux/selectors/signup/index.ts
Labels: backend, feature, fix, frontend

#183 FIX: 기존 lib/Image를 next/Image로 교체
  next/components/common/AuthContainer/index.tsx
  next/components/common/Image/index.tsx
  next/components/globalStyles/media.tsx
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
  next/components/landing/ContentBlock/LeftContentBlock/style.tsx
  next/components/landing/ContentBlock/RightContentBlock/index.tsx
  next/components/landing/ContentBlock/index.tsx
  next/pages/index.tsx
  next/typings/react-reveal.d.ts
Labels: fix, frontend, refactor

#187 FEATURE: 로그인 성공 시 만료 기한 필드 추가
  nest/controllers/auth.controller.ts
  nest/package-lock.json
  nest/package.json
Labels: backend, feature

#188 FEATURE: 채팅 관련 ORM 모델링 작성 & 사용자 본인 확인 Api 작성
  nest/controllers/user.controller.ts
  nest/models/entities/helper/abstract.ts
  nest/models/entities/room-user.entity.ts
  nest/models/entities/room.entity.ts
  nest/models/entities/user.entity.ts
  nest/models/repositories/user.repository.ts
  nest/test/e2e/user/mypage.e2e-spec.ts
  nest/typing/auth.ts
Labels: backend, feature, test

#189 FEAT: 채팅 페이지 프로토타입 퍼블리싱
  next/components/video-chat/CamSection/Cam/index.tsx
  next/components/video-chat/CamSection/Cam/style.tsx
  next/components/video-chat/CamSection/Container/index.tsx
  next/components/video-chat/CamSection/Container/style.tsx
  next/components/video-chat/CamSection/index.tsx
  next/components/video-chat/ChatSection/Chat/Announcement.tsx
  next/components/video-chat/ChatSection/Chat/FileChat.tsx
  next/components/video-chat/ChatSection/Chat/TextChat.tsx
  next/components/video-chat/ChatSection/Chat/index.tsx
  next/components/video-chat/ChatSection/Chat/style.tsx
  next/components/video-chat/ChatSection/ChatList/index.tsx
  next/components/video-chat/ChatSection/ChatList/style.tsx
  next/components/video-chat/ChatSection/Container/index.tsx
  next/components/video-chat/ChatSection/Container/style.tsx
  next/components/video-chat/ChatSection/InputBox/index.tsx
  next/components/video-chat/ChatSection/InputBox/style.tsx
  next/components/video-chat/ChatSection/index.tsx
  next/components/video-chat/Container/index.tsx
  next/components/video-chat/Container/style.tsx
  next/pages/video-chat.tsx
Labels: feature, frontend

#190 FIX: 프런트 자잘한 이슈 해결
  next/components/common/Button/index.tsx
  next/components/common/Button/style.tsx
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
  next/components/landing/ContentBlock/LeftContentBlock/style.tsx
  next/components/signup/End/index.tsx
  next/components/signup/OptionalInfo/index.tsx
  next/components/signup/RequiredInfo/index.tsx
  next/components/signup/Start/index.tsx
  next/hooks/useIsomorphicLayoutEffect.tsx
Labels: fix, frontend

#191 FEATURE: 채팅방 백엔드, 방생성, 존재여부 Api 작성, 프런트 Next 1차 SSR 적용
  nest/controllers/chat.controller.ts
  nest/models/repositories/room.repository.ts
  nest/modules/app.module.ts
  nest/modules/chat.module.ts
  nest/package-lock.json
  nest/package.json
  nest/seeders/user-props.ts
  next/components/video-chat/ChatSection/Chat/Announcement.tsx
  next/components/video-chat/ChatSection/Chat/FileChat.tsx
  next/components/video-chat/ChatSection/Chat/TextChat.tsx
  next/components/video-chat/ChatSection/Chat/index.tsx
  next/components/video-chat/ChatSection/Chat/style.tsx
  next/pages/chat/[id].tsx
Labels: backend, feature, frontend

#192 FIX: Next SSR 리턴 타입 수정
  next/pages/chat/[id].tsx
Labels: fix, frontend

#193 fix: globalStyles 타입 에러 해결
  next/components/globalStyles/index.tsx
  next/pages/_app.tsx
Labels: fix, frontend

#194 FEATURE: 프런트, 백엔드 소켓 시스템 확립, Api 구조 변경 및 안정성 향상, SSR 처리 로직 단순화
  nest/controllers/chat.controller.ts
  nest/controllers/chat.gateway.ts
  nest/modules/chat.module.ts
  nest/package-lock.json
  nest/package.json
  nest/services/chat.service.ts
  next/lib/enviroment.ts
  next/package-lock.json
  next/package.json
  next/pages/chat/[id].tsx
Labels: backend, frontend, refactor

#195 REFACTOR: antd 제거 - close #166
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
  next/components/landing/ContentBlock/RightContentBlock/index.tsx
  next/components/landing/Footer/index.tsx
  next/components/landing/Header/index.tsx
  next/components/landing/MiddleBlock/index.tsx
  next/package-lock.json
  next/package.json
  next/pages/_app.tsx
  next/pages/index.tsx
Labels: frontend, refactor

#196 FIX: 이메일 링크로 회원가입 진입 시 깜박임 문제 수정 - close #134
  next/components/signup/ProgressBar/index.tsx
  next/components/signup/ProgressBar/style.tsx
  next/components/signup/Start/index.tsx
  next/components/signup/Start/useEffectSignUpStart.tsx
  next/lib/apiClient.ts
  next/pages/signup.tsx
  next/redux/reducers/common/user.ts
  next/redux/reducers/index.ts
  next/redux/reducers/landing/index.ts
  next/redux/reducers/signup/index.ts
  next/redux/sagas/signup/index.ts
  next/redux/store/configureStore.ts
  next/typings/auth.ts
  next/typings/redux.d.ts
Labels: fix, frontend

#197 STYLE: alias 컨벤션 통일
  next/.babelrc
  next/components/common/Button/style.tsx
  next/components/common/Input/components.tsx
  next/components/common/ScrollTop/index.tsx
  next/components/common/ScrollTop/style.tsx
  next/components/landing/Container/style.tsx
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
  next/components/landing/ContentBlock/LeftContentBlock/style.tsx
  next/components/landing/ContentBlock/RightContentBlock/index.tsx
  next/components/landing/ContentBlock/RightContentBlock/style.tsx
  next/components/landing/Header/index.tsx
  next/components/landing/Header/style.tsx
  next/components/landing/MiddleBlock/style.tsx
  next/components/signup/End/index.tsx
  next/components/signup/OptionalInfo/index.tsx
  next/components/signup/RequiredInfo/Sections/ErrorSection.tsx
  next/components/signup/RequiredInfo/Sections/PasswordSection.tsx
  next/components/signup/RequiredInfo/Sections/TermSection.tsx
  next/components/signup/RequiredInfo/Sections/UsernameSection.tsx
  next/components/signup/RequiredInfo/index.tsx
  next/components/signup/Start/index.tsx
  next/components/signup/Start/style.tsx
  next/components/signup/common/styles.tsx
  next/components/video-chat/ChatSection/Chat/FileChat.tsx
  next/hooks/useTypedDispatch.ts
  next/hooks/useTypedSelector.ts
  next/lib/APIs.ts
  next/lib/apiClient.ts
  next/pages/_app.tsx
  next/pages/index.tsx
  next/pages/signup.tsx
  next/redux/reducers/common/user.ts
  next/redux/reducers/signup/index.ts
  next/redux/sagas/common/user.ts
  next/redux/sagas/signup/index.ts
  next/redux/selectors/common/user.ts
  next/redux/selectors/signup/index.ts
  next/tsconfig.json
  next/typings/auth.ts
Labels: frontend, style
