Repository bear-bear-bear/mogakco, pull requests merged in 2021-09, with the labels that each got.

#255 MODIFY: Backend 전체 구현 소스 src 디렉터리로 묶음 처리
  nest/controllers/dto/response.ts
  nest/jest.config.e2e.ts
  nest/jest.config.ts
  nest/main.ts
  nest/modules/user.module.ts
  nest/src/controllers/auth.controller.ts
  nest/src/controllers/chat.controller.ts
  nest/src/controllers/chat.gateway.ts
  nest/src/controllers/pipe/parse-join-pipe.ts
  nest/src/controllers/user.controller.ts
  nest/src/factory/helper/utils.ts
  nest/src/factory/users-field.factory.ts
  nest/src/factory/users-job.factory.ts
  nest/src/factory/users.factory.ts
  nest/src/guard/jwt-auth.guard.ts
  nest/src/guard/non-auth.guard.ts
  nest/src/lib/log.ts
  nest/src/lib/makeHash.ts
  nest/src/lib/promisifyJwtVerify.ts
  nest/src/lib/test-support.ts
  nest/src/lib/types/index.ts
  nest/src/models/entities/helper/abstract.ts
  nest/src/models/entities/room-user.entity.ts
  nest/src/models/entities/room.entity.ts
  nest/src/models/entities/user-field.entity.ts
  nest/src/models/entities/user-verify.entity.ts
  nest/src/models/entities/user.entity.ts
  nest/src/models/entities/users-job.entity.ts
  nest/src/models/repositories/ user-job.reposity.ts
  nest/src/models/repositories/room.repository.ts
  nest/src/models/repositories/user-field.repository.ts
  nest/src/models/repositories/user-verify.repository.ts
  nest/src/models/repositories/user.repository.ts
  nest/src/modules/app.module.ts
  nest/src/modules/auth.module.ts
  nest/src/modules/chat.module.ts
  nest/src/modules/mail.module.ts
  nest/src/modules/user.module.ts
  nest/src/seeders/user-props.ts
  nest/src/services/auth.service.ts
  nest/src/services/chat.service.ts
  nest/src/services/email.service.ts
  nest/src/services/email/user-verify.pug
  nest/src/services/passport/jwt-guard.ts
  nest/src/services/passport/jwt.refresh.guard.ts
  nest/src/services/passport/jwt.refresh.strategy.ts
  nest/src/services/passport/jwt.strategy.ts
  nest/src/services/passport/local-auth.guard.ts
  nest/src/services/passport/local.strategy.ts
  nest/src/services/user.service.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  nest/test/e2e/user/mypage.e2e-spec.ts
  nest/test/e2e/user/user-props.e2e-spec.ts
  nest/tsconfig.json
  nest/typing/auth.ts
Labels: refactor, backend

#257 REMOVE: authentication 디렉터리 구조 변환을 위한 파일 삭제 - Priority 0
  nest/jest.config.e2e.ts
  nest/jest.config.ts
  nest/src/modules/app.module.ts
  nest/src/modules/auth.module.ts
  nest/src/modules/chat.module.ts
  nest/src/services/auth.service.ts
  nest/src/services/passport/jwt-guard.ts
  nest/src/services/passport/jwt.refresh.guard.ts
  nest/src/services/passport/jwt.refresh.strategy.ts
  nest/src/services/passport/jwt.strategy.ts
  nest/src/services/passport/local-auth.guard.ts
  nest/src/services/passport/local.strategy.ts
  nest/tsconfig.json
Labels: refactor, backend

#258 MODIFY: authentication 디렉터리로 분리 - - Priority 1
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/auth.module.ts
  nest/src/authentication/auth.service.ts
  nest/src/authentication/strategies/jwt.refresh.strategy.ts
  nest/src/authentication/strategies/jwt.strategy.ts
  nest/src/authentication/strategies/local.strategy.ts
  nest/src/controllers/pipe/parse-join-pipe.ts
  nest/src/controllers/user.controller.ts
  nest/src/lib/jwt-promise.ts
Labels: refactor, backend

#261 FEATURE: 테스트 애플리케이션 반환 함수 작성 및 e2e 반영
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  nest/test/e2e/helper/module.ts
  nest/test/e2e/user/mypage.e2e-spec.ts
  nest/test/e2e/user/user-props.e2e-spec.ts
Labels: test, refactor, backend

#259 MODIFY: common 분기 처리 및 모듈 재배치 - Priority 2
  nest/jest.config.e2e.ts
  nest/jest.config.ts
  nest/main.ts
  nest/src/app.module.ts
  nest/src/common/guards/jwt-auth.guard.ts
  nest/src/common/guards/jwt-guard.ts
  nest/src/common/guards/jwt-refresh.guard.ts
  nest/src/common/guards/non-auth.guard.ts
  nest/src/common/pipes/parse-join-pipe.ts
  nest/src/models/entities/room-user.entity.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  nest/test/e2e/user/mypage.e2e-spec.ts
  nest/test/e2e/user/user-props.e2e-spec.ts
  nest/tsconfig.json
Labels: refactor, backend

#263 fix: 커밋 전 린트 자동 수행 기능 추가, 백엔드 각종 문제 수정
  .gitignore
  nest/.eslintrc.js
  nest/.eslintrc.json
  nest/.husky/pre-commit
  nest/config/app/config.module.ts
  nest/jest.config.e2e.ts
  nest/jest.config.ts
  nest/package-lock.json
  nest/package.json
  nest/src/app.module.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  nest/test/e2e/helper/module.ts
  nest/test/e2e/user/mypage.e2e-spec.ts
  nest/test/e2e/user/user-props.e2e-spec.ts
  nest/tsconfig.json
  next/.husky/pre-commit
  next/package-lock.json
  next/package.json
  next/test.js
  package-lock.json
  package.json
Labels: fix, help wanted, feature, frontend, backend

#262 FEATURE: 데이터베이스 모듈 작성 및 분리 적용
  nest/src/config/database/mariadb.module.ts
Labels: refactor, backend

#264 FIX: Seed 오류 수정 및 변경 사항 반영, Dto 변경
  nest/.env.example
  nest/nest-cli.json
  nest/src/app.module.ts
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/auth.service.ts
  nest/src/authentication/dto/create-user.dto.ts
  nest/src/authentication/dto/login-user.dto.ts
  nest/src/config/app/config.module.ts
  nest/src/main.ts
  nest/src/models/repositories/user.repository.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
  nest/tsconfig.json
  nest/typing/auth.ts
Labels: fix, backend

#265 FIX: swr retry 제한
  next/hooks/useUser.tsx
Labels: fix, frontend

#266 feat: test 관련 모듈과 디렉터리 삭제
  .github/workflows/node.js.yml
  next/cypress.json
  next/package-lock.json
  next/package.json
  next/test.js
  next/test/e2e/cypress/tsconfig.json
  next/test/e2e/integration/landing.test.ts
  next/test/unit/frontend/components/TestRenderer.test.tsx
  next/test/unit/frontend/pages/TestRenderer.spec.tsx
  next/test/unit/frontend/test-config.json
Labels: feature, frontend

#267 FEAT: 디렉터리 구조 변경
  nest/.env.example
  nest/nest-cli.json
  nest/src/app.module.ts
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/auth.module.ts
  nest/src/authentication/auth.service.ts
  nest/src/authentication/dto/create-user.dto.ts
  nest/src/common/helpers/entity.helper.ts
  nest/src/common/helpers/test.helper.ts
  nest/src/config/database/mariadb.module.ts
  nest/src/database/factories/helper/utils.ts
  nest/src/database/factories/users-field.factory.ts
  nest/src/database/factories/users-job.factory.ts
  nest/src/database/factories/users.factory.ts
  nest/src/database/seeders/user-props.ts
  nest/src/mail/assets/user-verify.pug
  nest/src/mail/email.service.ts
  nest/src/mail/mail.module.ts
  nest/src/models/chat/chat.controller.ts
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.module.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/entities/room-user.entity.ts
  nest/src/models/chat/entities/room.entity.ts
  nest/src/models/chat/repositories/room.repository.ts
  nest/src/models/user/entities/user-field.entity.ts
  nest/src/models/user/entities/user-verify.entity.ts
  nest/src/models/user/entities/user.entity.ts
  nest/src/models/user/entities/users-job.entity.ts
  nest/src/models/user/repositories/ user-job.reposity.ts
  nest/src/models/user/repositories/user-field.repository.ts
  nest/src/models/user/repositories/user-verify.repository.ts
  nest/src/models/user/repositories/user.repository.ts
  nest/src/models/user/user.controller.ts
  nest/src/models/user/user.module.ts
  nest/src/models/user/user.service.ts
  nest/src/modules/chat.module.ts
  nest/src/modules/user.module.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
  nest/tsconfig.json
  nest/typing/auth.ts
Labels: refactor, backend

#268 npm: nest 7 -> nest 8 업데이트
  nest/.eslintrc.js
  nest/.eslintrc.json
  nest/package-lock.json
  nest/package.json
  nest/src/models/user/entities/user-verify.entity.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/tsconfig.json
Labels: backend

#269 TEST: Swagger 환경 설정 및 인증 관련 Swagger Document 작성
  nest/main.ts
  nest/package-lock.json
  nest/package.json
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/auth.service.ts
  nest/src/authentication/dto/create-user.dto.ts
  nest/src/authentication/dto/login-user.dto.ts
  nest/src/common/decorators/swagger/auth.decorator.ts
  nest/src/common/helpers/app.helper.ts
  nest/src/common/helpers/enum.helper.ts
  nest/src/models/user/entities/user-field.entity.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
Labels: test, backend

#270 npm: 프런트엔드 패키지 업데이트
  next/package-lock.json
  next/package.json
Labels: frontend

#273 fix: 데이터베이스 시더 에러 수정 - 우선순위 1
  nest/.env.example
  nest/src/common/helpers/test.helper.ts
Labels: fix, test, backend

#274 feature: ORM 관련 코드 리팩터링 및 리포지토리 유닛 테스트 작성
  nest/src/models/user/entities/user-field.entity.ts
  nest/src/models/user/repositories/user.repository.ts
  nest/test/unit/services/dto/update-user-request.dto.ts
  nest/test/unit/services/user.test.ts
  nest/test/unit/user/index.test.ts
  nest/test/unit/user/user.repository.test.ts
  nest/typing/auth.ts
Labels: feature, test, refactor, backend

#271 feature: 백엔드 Swagger 작성 및 기존 로직 리팩터링
  nest/nest-cli.json
  nest/src/authentication/auth.service.ts
  nest/src/authentication/strategies/jwt.refresh.strategy.ts
  nest/src/authentication/strategies/jwt.strategy.ts
  nest/src/common/decorators/swagger/auth.decorator.ts
  nest/src/common/decorators/swagger/chat.decorator.ts
  nest/src/common/helpers/decorator.helper.ts
  nest/src/common/helpers/enum.helper.ts
  nest/src/common/helpers/jwt-promise.helper.ts
  nest/src/common/helpers/make-hash.helper.ts
  nest/src/database/seeders/user-props.ts
  nest/src/lib/log.ts
  nest/src/lib/makeHash.ts
  nest/src/lib/types/index.ts
  nest/src/mail/email.service.ts
Labels: feature, test, refactor, backend

#272 feature: 기존 로직 리팩터링 연계 PR
  nest/src/models/chat/chat.controller.ts
  nest/src/models/user/entities/user.entity.ts
  nest/src/models/user/repositories/ user-job.reposity.ts
  nest/tsconfig.json
  nest/typing/auth.ts
Labels: feature, test, refactor, backend

#276 feat: swagger 인증 수단에 refreshToken 추가
  nest/src/common/helpers/app.helper.ts
Labels: feature, test, backend

#277 fix: 프런트엔드 오류 수정
  next/next.config.js
  next/package-lock.json
  next/package.json
Labels: fix, frontend

#279 fix: 누락된 401 정보 입력 & Swagger 누락사항 작성
  nest/src/authentication/auth.controller.ts
  nest/src/common/decorators/swagger/auth.decorator.ts
Labels: fix, test, backend

#280 fix: httponly 설정에 따라 기존 document.cookie 사용 로직 주석처리, risk 주시할것
  next/lib/apiClient.ts
Labels: risk, frontend

#281 ci: 프런트엔드 패키지 인스톨 속도 향상
  .github/workflows/node.js.yml
  nest/test/e2e/auth/user-login.e2e-spec.ts
  next/package.json
Labels: feature, frontend

#283 fix: 메일 테스트 에러 해결
  nest/.env.example
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  nest/test/e2e/user/mypage.e2e-spec.ts
  nest/test/e2e/user/user-props.e2e-spec.ts
Labels: fix, backend

#282 test: login 테스트 skip 해제
  nest/src/common/decorators/swagger/auth.decorator.ts
  nest/src/mail/mail.module.ts
  nest/src/models/user/repositories/user.repository.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  nest/typing/common.ts
  nest/typing/example.ts
Labels: fix, test, backend

#284 feat: 이슈 템플릿 추가
  .github/ISSUE_TEMPLATE/api-request.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: feature

#286 fix: /api/auth/user statusCode 이슈 수정
  nest/src/authentication/auth.controller.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
Labels: fix, backend

#287 feat: Socket.io 4.2.3 으로 Server, Client Socket 연결 작성
  nest/package-lock.json
  nest/package.json
  nest/src/models/chat/chat.gateway.ts
  next/hooks/useSocket.tsx
  next/hooks/useSocketTest.tsx
  next/pages/video-chat/[id].tsx
Labels: feature, frontend, backend

#288 feat: 로고 추가
  next/components/common/AuthContainer/index.tsx
  next/components/common/CustomHead/index.tsx
  next/components/landing/Header/style.tsx
  next/public/assets/svg/logo1.svg
  next/public/assets/svg/logo2.svg
Labels: feature, frontend

#291 feature: 프런트엔드 타입 관련 에러 수정 및 소켓 훅 작성
  nest/src/authentication/dto/login-user.dto.ts
  nest/src/models/chat/entities/room-user.entity.ts
  nest/src/models/chat/entities/room.entity.ts
  nest/src/models/chat/repositories/room-user.repository.ts
  next/components/sign-in/index.tsx
  next/components/sign-up/Optional/index.tsx
  next/components/video-chat/ChatSection/InputBox/index.tsx
  next/hooks/useSocket.tsx
  next/hooks/useSocketTest.tsx
  next/hooks/useUser.tsx
  next/pages/dashboard/index.tsx
  next/pages/video-chat/[id].tsx
Labels: fix, feature, test, frontend, backend

#292 test: 테스트 가독성 향상 및 /api/auth 테스트 추가 케이스 작성
  nest/src/authentication/auth.controller.ts
  nest/src/common/decorators/swagger/auth.decorator.ts
  nest/test/e2e/auth/email-verification.e2e-spec.ts
  nest/test/e2e/auth/user-join.e2e-spec.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  nest/test/e2e/helper/enum.ts
Labels: test, refactor, backend

#294 fix: 인증 기능 오류 수정 및 리팩터링
  nest/main.ts
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/auth.module.ts
  nest/src/authentication/auth.service.ts
  nest/src/authentication/strategies/jwt.refresh.strategy.ts
  nest/src/authentication/strategies/jwt.strategy.ts
  nest/src/common/exceptions/http-exception.filter.ts
  nest/src/common/guards/jwt-guard.ts
  nest/src/common/guards/jwt-refresh.guard.ts
Labels: fix, feature, refactor, backend

#297 feature: 백엔드 리팩터링 및 예외 처리 보충
  nest/main.ts
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/auth.module.ts
  nest/src/authentication/jwt.module.ts
  nest/src/authentication/strategies/local.strategy.ts
  nest/src/common/decorators/swagger/auth.decorator.ts
  nest/src/common/exceptions/no-user-exception.filter.ts
  nest/src/common/guards/jwt-refresh.guard.ts
  nest/src/common/helpers/app.helper.ts
  nest/src/config/database/mariadb.module.ts
  nest/src/models/user/repositories/user.repository.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
Labels: fix, feature, test, refactor, backend

#296 feat: 로그아웃 상태일 때 accessToken 갱신 방지
  nest/src/authentication/auth.service.ts
  next/components/sign-in/index.tsx
  next/components/sign-up/Optional/index.tsx
  next/hooks/useUser.tsx
  next/lib/apiClient.ts
  next/lib/token.ts
  next/pages/dashboard/index.tsx
  next/pages/sign-in/index.tsx
  next/pages/sign-up/optional.tsx
Labels: feature, frontend

#298 feat: useUser 보완
  next/hooks/useUser.tsx
  next/lib/apiClient.ts
  next/lib/token.ts
Labels: feature, refactor, frontend

#300 feat: 소켓 서버, 채팅에 대한 기능 추가
  nest/src/common/decorators/swagger/chat.decorator.ts
  nest/src/models/chat/chat.controller.ts
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.module.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/entities/chat.entity.ts
  nest/src/models/user/entities/user.entity.ts
  nest/src/models/user/repositories/chat.repository.ts
  next/components/video-chat/ChatSection/ChatList/index.tsx
  next/hooks/useSocket.tsx
  next/hooks/useUser.tsx
  next/package-lock.json
  next/package.json
Labels: fix, feature, test, frontend, backend

#302 feat: API 요청 수정
  nest/src/authentication/auth.controller.ts
Labels: backend, request change

#301 feat: 채팅 구현
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/user/repositories/chat.repository.ts
  next/components/video-chat/ChatSection/Chat/Announcement.tsx
  next/components/video-chat/ChatSection/Chat/MyTextChat.tsx
  next/components/video-chat/ChatSection/Chat/index.tsx
  next/components/video-chat/ChatSection/Chat/style.tsx
  next/components/video-chat/ChatSection/ChatList/index.tsx
  next/components/video-chat/ChatSection/InputBox/index.tsx
Labels: feature, frontend, backend

#304 fix: useUser 타입문제 수정
  nest/src/authentication/auth.controller.ts
  next/hooks/useUser.tsx
  next/pages/dashboard/index.tsx
  next/pages/video-chat/[id].tsx
  next/typings/auth.ts
Labels: fix, frontend

#299 refactor: 인증 도메인 관심사 분리 추가
  nest/src/app.module.ts
  nest/src/authentication/auth.module.ts
  nest/src/authentication/modules/auth.module.ts
  nest/src/authentication/modules/jwt.module.ts
  nest/src/authentication/modules/shared.module.ts
  nest/src/models/chat/chat.module.ts
Labels: refactor, backend

#307 feat: 여러 서비스 페이지에서 쓰일 프로필 컴포넌트 추가
  next/components/common/Profile/ProfileModal.tsx
  next/components/common/Profile/index.tsx
  next/components/common/Profile/style.tsx
  next/components/common/ServiceHeader/index.tsx
  next/components/common/ServiceHeader/style.tsx
  next/components/globalStyles/_Resets.tsx
  next/components/my-page/Header/index.tsx
  next/pages/my-page/account-setting.tsx
  next/pages/my-page/calendar.tsx
  next/pages/my-page/index.tsx
Labels: feature, frontend

#306 refactor: 채팅 도메인 리팩터링
  nest/src/models/chat/chat.controller.ts
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.module.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/interface/controller.ts
  nest/src/models/chat/interface/gateway.ts
  nest/src/models/chat/interface/service.ts
  nest/src/models/chat/repositories/chat.repository.ts
  nest/src/models/chat/repositories/room-user.repository.ts
  nest/src/models/chat/repositories/room.repository.ts
Labels: refactor, backend

#308 feat: 서비스 헤더를 대시보드 페이지에도 적용하고 그에 맞춰 스타일 보완
  next/components/common/Profile/ProfileModal.tsx
  next/components/common/Profile/index.tsx
  next/components/common/Profile/style.tsx
  next/components/common/ServiceHeader/style.tsx
  next/components/dashboard/Container/style.tsx
  next/components/globalStyles/_Variables.tsx
  next/components/globalStyles/index.tsx
  next/components/my-page/Container/style.tsx
  next/pages/dashboard/index.tsx
  next/pages/my-page/account-setting.tsx
  next/pages/my-page/calendar.tsx
  next/pages/my-page/index.tsx
Labels: feature, frontend

#309 refactor: global 모듈 적용
  nest/src/authentication/modules/shared.module.ts
  nest/src/config/database/mariadb.module.ts
  nest/src/models/chat/chat.module.ts
  nest/src/models/user/user.module.ts
Labels: refactor, backend

#305 test: swagger response case 보충 및 HttpStatus 교체
  nest/src/common/decorators/swagger/auth.decorator.ts
  nest/src/common/decorators/swagger/chat.decorator.ts
Labels: test, backend

#310 feat: 입 퇴장 프런트 백엔드 구현
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/interface/gateway.ts
  next/components/video-chat/ChatSection/Chat/Announcement.tsx
  next/components/video-chat/ChatSection/Chat/index.tsx
  next/components/video-chat/ChatSection/ChatList/index.tsx
  next/typings/chat.ts
Labels: feature, frontend, backend

#311 feat: 외부 프로덕션 혹은 테스트 접속 주소 설정
  nest/.env.example
  nest/src/authentication/auth.controller.ts
  next/lib/apiClient.ts
Labels: frontend, backend

#312 fix: I 자존감 낮추기
  next/components/common/AuthContainer/index.tsx
  next/components/dashboard/CardLink/index.tsx
  next/components/landing/ContentBlock/LeftContentBlock/index.tsx
  next/components/landing/ContentBlock/RightContentBlock/index.tsx
Labels: fix

#315 feat: nextjs migration
  next/components/globalStyles/index.tsx
  next/next.config.js
  next/package-lock.json
Labels: feature, frontend

#317 feat: 모델링 + 프로덕션에 대한 코드 수정
  nest/package-lock.json
  nest/package.json
  nest/src/authentication/auth.controller.ts
  nest/src/common/decorators/swagger/auth.decorator.ts
  nest/src/config/database/mariadb.module.ts
  nest/src/mail/assets/user-verify.pug
  nest/src/mail/email.service.ts
  nest/src/models/chat/entities/anonymous-room-user.entity.ts
  nest/src/models/chat/entities/chat-file.entity.ts
  nest/src/models/chat/entities/room.entity.ts
  nest/src/models/chat/repositories/anonymous-room-user.repository.ts
  nest/src/models/chat/repositories/chat-file.repository.ts
  nest/src/models/user/entities/user.entity.ts
Labels: fix, feature, test, backend

#323 feat: 익명 채팅 및 멤버 수 표기 기능 작성
  nest/src/models/chat/chat.controller.ts
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/repositories/room-user.repository.ts
  nest/src/models/user/user.controller.ts
  nest/src/models/user/user.service.ts
  nest/test/e2e/user/user-props.e2e-spec.ts
  next/src/components/video-chat/ChatSection/ChatList/index.tsx
  next/src/components/video-chat/ChatSection/Container/index.tsx
  next/src/components/video-chat/ChatSection/Container/style.tsx
  next/src/components/video-chat/ChatSection/InputBox/index.tsx
  next/src/components/video-chat/ChatSection/index.tsx
  next/src/hooks/useSocket.tsx
  next/src/pages/video-chat/[id].tsx
  next/typings/chat.ts
Labels: fix, feature, frontend, backend

#326 feat: 배포 환경 설정
  nest/main.ts
  nest/package-lock.json
  nest/package.json
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/auth.service.ts
  nest/typing/auth.ts
Labels: feature, backend

#325 refactor: 백엔드/프런트엔드 소켓 서비스 부분 리팩터링
  nest/src/common/decorators/swagger/chat.decorator.ts
  nest/src/models/chat/chat.controller.ts
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/interface/controller.ts
  nest/src/models/chat/interface/gateway.ts
  nest/src/models/chat/interface/service.ts
  next/src/components/video-chat/ChatSection/ChatList/index.tsx
  next/src/components/video-chat/ChatSection/Container/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/index.tsx
  next/src/components/video-chat/ChatSection/index.tsx
  next/src/hooks/useSocket.tsx
  next/src/pages/video-chat/[id].tsx
Labels: refactor, frontend, backend

#327 feat: 개발 환경에 대해 분기 처리 및 테스트 및 프로덕션 로직 오류 수정
  nest/.env.example
  nest/main.ts
  nest/src/common/helpers/enum.helper.ts
  nest/src/config/app/config.module.ts
  nest/src/mail/assets/user-verify.pug
  nest/src/mail/email.service.ts
  nest/src/mail/mail.module.ts
  next/.env
  next/package-lock.json
  next/package.json
  next/src/components/video-chat/ChatSection/Chat/Announcement.tsx
  next/src/components/video-chat/ChatSection/Chat/index.tsx
  next/src/hooks/useSocket.tsx
  next/src/lib/apiClient.ts
  next/src/lib/enviroment.ts
Labels: fix, feature, frontend, backend

#328 fix: 빠른 수정
  nest/src/mail/assets/user-verify.pug
  next/src/lib/enviroment.ts
Labels: fix

#329 fix: nextjs 환경변수 문제 수정
  next/.env
  next/.env.development
  next/.env.production
  next/src/components/common/Profile/ProfileModal.tsx
  next/src/components/sign-in/index.tsx
  next/src/hooks/useSocket.tsx
  next/src/lib/apiClient.ts
  next/src/lib/enviroment.ts
  next/src/pages/_app.tsx
Labels: fix, frontend

#330 !HOTFIX: env 실수 긴급 수정
  next/.env
  next/.env.development
  next/.env.production
  next/src/lib/enviroment.ts
Labels: fix, frontend

#332 feat: 백엔드 채팅방 자동 찾기 및 생성 Api 구현
  nest/src/common/decorators/swagger/chat.decorator.ts
  nest/src/database/seeders/user-props.ts
  nest/src/models/chat/chat.controller.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/entities/room.entity.ts
  nest/src/models/chat/interface/controller.ts
  nest/src/models/chat/interface/service.ts
  nest/src/models/chat/repositories/room.repository.ts
  nest/src/models/user/user.service.ts
Labels: feature, backend

#334 fix: 프로덕션 잔버그 수정 및 유저 부속 정보 Api 개선 및 오픈
  nest/.env.example
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/auth.service.ts
  nest/src/common/decorators/swagger/user.decorator.ts
  nest/src/config/app/config.module.ts
  nest/src/mail/email.service.ts
  nest/src/models/user/interface/controller.ts
  nest/src/models/user/repositories/user.repository.ts
  nest/src/models/user/user.controller.ts
  nest/src/models/user/user.service.ts
Labels: fix, backend

#335 feat: 사용자 역할 관련 모델링 작성 및 서버 반영
  nest/src/config/database/mariadb.module.ts
  nest/src/models/chat/entities/roles.entity.ts
  nest/src/models/chat/entities/user-roles.entity.ts
  nest/src/models/chat/repositories/roles.repository.ts
  nest/src/models/chat/repositories/user-roles.repository.ts
Labels: feature, backend

#336 feat: 방 찾기 또는 생성 api 프런트엔드 연동
  next/src/components/dashboard/CardLink/Card.tsx
  next/src/lib/apis.ts
  next/src/pages/dashboard/index.tsx
  next/typings/auth.ts
Labels: feature, frontend

#322 feat: my-page 계정 설정 페이지 UI/UX, validation 구현
  next/package.json
  next/src/components/common/Button/index.tsx
  next/src/components/common/Button/style.tsx
  next/src/components/common/Input/style.tsx
  next/src/components/common/Select/index.tsx
  next/src/components/common/Select/stylesConfig.ts
  next/src/components/my-page/AccountSetting/index.tsx
  next/src/components/my-page/AccountSetting/style.tsx
  next/src/components/my-page/Container/index.tsx
  next/src/components/my-page/Container/style.tsx
  next/src/components/sign-up/Optional/JobSelect.tsx
  next/src/components/sign-up/Optional/SkillsSelect.tsx
  next/src/components/sign-up/Optional/index.tsx
  next/src/lib/toSelectOptions.ts
  next/src/pages/my-page/account-setting.tsx
  next/src/pages/sign-up/optional.tsx
Labels: feature, frontend

#338 feat: 채팅방 인원 수에 따른 자동 제거 구현
  nest/src/database/seeders/user-props.ts
  nest/src/models/chat/chat.controller.ts
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/entities/room.entity.ts
  nest/src/models/chat/interface/service.ts
  nest/src/models/chat/repositories/room.repository.ts
  nest/src/models/user/entities/user.entity.ts
Labels: feature, backend

#340 test: 유저 희망 분야, 직업 객체 리스트 정보 불러오기 api e2e 테스트 작성
  nest/test/e2e/user/user-props.e2e-spec.ts
  nest/test/type/mock-data-type.ts
Labels: test, backend

#343 fix: 백엔드 응답 변경에 맞춰 타입과 코드 수정 #341
  next/src/lib/apis.ts
  next/src/pages/sign-up/optional.tsx
  next/typings/auth.ts
Labels: fix, frontend

#342 feat: 서비스 채팅 다중 유저 방지 기능 작성
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/interface/gateway.ts
  nest/src/models/chat/interface/service.ts
  nest/src/models/chat/repositories/anonymous-room-user.repository.ts
  next/src/components/video-chat/ChatSection/Chat/index.tsx
  next/src/pages/video-chat/[id].tsx
  next/typings/chat.ts
Labels: feature, frontend, backend

#344 feat: 채팅 서비스 안정성 향상
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/interface/service.ts
  next/.env.production
  next/src/hooks/video-chat/useChatError.tsx
  next/src/pages/video-chat/[id].tsx
Labels: refactor, frontend, backend

#346 feat: 유저 역할 로직 구현과 시드 전반적 개선 및 추가 시더 작성
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/auth.service.ts
  nest/src/config/database/mariadb.module.ts
  nest/src/database/seeders/a1-jobs-and-fields.ts
  nest/src/database/seeders/a2-basic-roles.ts
  nest/src/database/seeders/a3-fake-users.ts
  nest/src/database/seeders/a3-test-users.ts
  nest/src/database/seeders/user-props.ts
  nest/src/models/chat/entities/user-roles.entity.ts
  nest/src/models/chat/repositories/user-roles.repository.ts
  nest/src/models/user/entities/roles.entity.ts
  nest/src/models/user/entities/user-roles.entity.ts
  nest/src/models/user/repositories/roles.repository.ts
  nest/src/models/user/repositories/user-roles.repository.ts
Labels: feature, test, backend

#347 feat: 어드민 및 어드민 전용 인증 구현
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/modules/jwt.module.ts
  nest/src/authentication/strategies/jwt-admin.strategy.ts
  nest/src/common/decorators/swagger/auth.decorator.ts
  nest/src/common/guards/admin.guard.ts
  nest/src/common/guards/non-auth.guard.ts
  nest/src/database/seeders/a3-test-admin-user.ts
  nest/src/models/user/entities/user-roles.entity.ts
Labels: feature, test, backend

#349 fix: 유저 put 요청 타입에 id 추가, 관련 Next api 가독성 개선
  next/src/components/my-page/AccountSetting/index.tsx
  next/src/pages/api/user/index.ts
  next/typings/auth.ts
Labels: fix, frontend

#350 feat: 대쉬보드 카드 style 보완
  next/src/components/common/ServiceHeader/style.tsx
  next/src/components/dashboard/Card/CardAnchor.tsx
  next/src/components/dashboard/Card/CardButton.tsx
  next/src/components/dashboard/Card/index.tsx
  next/src/components/dashboard/Card/style.tsx
  next/src/components/dashboard/CardLink/Card.tsx
  next/src/components/dashboard/CardLink/index.tsx
  next/src/components/dashboard/Container/style.tsx
  next/src/pages/dashboard/index.tsx
Labels: fix, feature, frontend

#352 feat: 채팅방 입장 전 UX 작업 - close #337
  next/src/components/common/Button/style.tsx
  next/src/components/dashboard/Card/CardAnchor.tsx
  next/src/components/dashboard/Card/CardButton.tsx
  next/src/components/dashboard/Card/index.tsx
  next/src/components/dashboard/Card/style.tsx
  next/src/components/dashboard/Container/index.tsx
  next/src/components/video-chat/Container/style.tsx
  next/src/components/video-chat/Loading/index.tsx
  next/src/components/video-chat/Loading/style.tsx
  next/src/lib/apis.ts
  next/src/pages/dashboard/index.tsx
  next/typings/auth.ts
Labels: feature, frontend

#351 feature: 사용자 업데이트 와 삭제 Api 구현
  nest/.env.example
  nest/src/authentication/dto/update-user.dto.ts
  nest/src/common/decorators/swagger/user.decorator.ts
  nest/src/common/interface/global.ts
  nest/src/models/user/interface/controller.ts
  nest/src/models/user/interface/service.ts
  nest/src/models/user/repositories/user.repository.ts
  nest/src/models/user/user.controller.ts
  nest/src/models/user/user.module.ts
  nest/src/models/user/user.service.ts
  nest/test/e2e/helper/enum.ts
  nest/test/e2e/helper/user.ts
  nest/test/e2e/user/delete.e2e-spec.ts
  nest/test/e2e/user/update.e2e-spec.ts
Labels: feature, test, backend

#353 fix: 채팅 UI 급한 부분만 임시 보정, 리팩터링 필요부분 손질
  next/package-lock.json
  next/package.json
  next/src/components/dashboard/Loading/index.tsx
  next/src/components/dashboard/Loading/style.tsx
  next/src/components/video-chat/ChatSection/Chat/Announcement.tsx
  next/src/components/video-chat/ChatSection/Chat/FileChat.tsx
  next/src/components/video-chat/ChatSection/Chat/MyTextChat.tsx
  next/src/components/video-chat/ChatSection/Chat/TextChat.tsx
  next/src/components/video-chat/ChatSection/Chat/index.tsx
  next/src/components/video-chat/ChatSection/Chat/style.tsx
  next/src/components/video-chat/ChatSection/ChatList/index.tsx
  next/src/components/video-chat/ChatSection/ChatList/style.tsx
  next/src/components/video-chat/ChatSection/Container/index.tsx
  next/src/components/video-chat/ChatSection/Container/style.tsx
  next/src/components/video-chat/ChatSection/InputBox/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/style.tsx
  next/src/pages/dashboard/index.tsx
  next/src/pages/video-chat/[id].tsx
  next/typings/chat.ts
Labels: fix, refactor, frontend

#355 feat: 채팅방 레이아웃 수정, 채팅창 on/off 기능 구현, 자잘한 스타일 문제 수정
  next/package-lock.json
  next/public/svg/calendar.svg
  next/public/svg/conversation.svg
  next/public/svg/logo2.svg
  next/src/components/video-chat/CamSection/Container/style.tsx
  next/src/components/video-chat/ChatSection/Container/index.tsx
  next/src/components/video-chat/ChatSection/Container/style.tsx
  next/src/components/video-chat/ChatSection/InputBox/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/style.tsx
  next/src/components/video-chat/ChatSection/index.tsx
  next/src/components/video-chat/Sidebar/index.tsx
  next/src/components/video-chat/Sidebar/style.tsx
  next/src/pages/video-chat/[id].tsx
Labels: fix, feature, frontend

#356 feat: 익명 사용자에 대한 기능과 Api 추가
  nest/src/common/decorators/swagger/chat.decorator.ts
  nest/src/database/seeders/a4-test-anonymous-props.ts
  nest/src/models/chat/chat.controller.ts
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/dto/anonymous-prop.dto.ts
  nest/src/models/chat/entities/anonymous_names.entity.ts
  nest/src/models/chat/entities/anonymous_prefix.entity.ts
  nest/src/models/chat/interface/controller.ts
  nest/src/models/chat/interface/service.ts
  nest/src/models/chat/repositories/anonymous-room-user.repository.ts
  nest/src/models/user/entities/user.entity.ts
  nest/test/e2e/helper/enum.ts
  next/src/hooks/useSocket.tsx
Labels: feature, backend

#358 feat: 익명에 관한 Api 목록 작성
  nest/src/common/decorators/swagger/chat.decorator.ts
  nest/src/models/chat/chat.controller.ts
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.service.ts
  nest/src/models/chat/interface/controller.ts
  nest/src/models/chat/interface/service.ts
Labels: feature, test, backend

#357 fix: 09-23 기준 일자 백엔드 이슈 항목 처리
  nest/src/app.module.ts
  nest/src/authentication/auth.controller.ts
  nest/src/authentication/interfaces/test-interface.ts
  nest/src/authentication/modules/test.module.ts
  nest/src/authentication/test/test.controller.ts
  nest/src/common/decorators/swagger/auth.decorator.ts
  nest/src/common/helpers/enum.helper.ts
  nest/src/models/user/interface/controller.ts
  nest/src/models/user/repositories/user.repository.ts
  nest/src/models/user/user.controller.ts
  nest/test/e2e/auth/user-login.e2e-spec.ts
  nest/test/unit/user/user.repository.test.ts
Labels: fix, backend

#360 feat: 에디터 도입 및 채팅관련 이슈 해결
  next/package-lock.json
  next/package.json
  next/public/svg/edit.svg
  next/src/components/video-chat/ChatSection/Chat/TextChat.tsx
  next/src/components/video-chat/ChatSection/Chat/style.tsx
  next/src/components/video-chat/ChatSection/ChatList/index.tsx
  next/src/components/video-chat/ChatSection/ChatList/style.tsx
  next/src/components/video-chat/ChatSection/InputBox/SVGButton.tsx
  next/src/components/video-chat/ChatSection/InputBox/TuiEditor.tsx
  next/src/components/video-chat/ChatSection/InputBox/TuiEditorWrapper.tsx
  next/src/components/video-chat/ChatSection/InputBox/colourableLanguages.ts
  next/src/components/video-chat/ChatSection/InputBox/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/style.tsx
Labels: fix, feature, frontend

#361 feat: 채팅 추가 시 스크롤 bottom으로 가도록 추가
  next/src/components/video-chat/ChatSection/ChatList/index.tsx
Labels: feature, frontend

#362 feat: 계정 설정 페이지 mock api를 추가된 nest api로 대체
  next/src/components/my-page/AccountSetting/index.tsx
  next/src/lib/apis.ts
  next/src/pages/api/example.ts
  next/src/pages/api/user/index.ts
Labels: help wanted, feature, frontend

#363 refactor: 채팅 서비스 리팩터링 및 room 과 socket.io 연동 기능
  nest/src/common/helpers/enum.helper.ts
  nest/src/models/chat/chat.gateway.ts
  nest/src/models/chat/chat.service.ts
  next/src/components/video-chat/ChatSection/ChatList/index.tsx
  next/src/components/video-chat/ChatSection/Container/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/index.tsx
  next/src/hooks/chat/useChatClient.tsx
  next/src/hooks/chat/useChatEvent.tsx
  next/src/hooks/chat/useHandleChatErrorEvent.tsx
  next/src/hooks/useSocket.tsx
  next/src/hooks/video-chat/useChatError.tsx
  next/src/lib/enum.ts
  next/src/lib/getChatSocket.ts
  next/src/pages/video-chat/[id].tsx
Labels: fix, feature, refactor, frontend, backend

#366 fix: 서비스 페이지에서 useUser 요청 도중 user가 undefined일때 나타나는 랜딩페이지 flash fix
  next/src/pages/index.tsx
Labels: fix, frontend

#365 feat: 새로운 채팅 추가 시 스크롤 방식 변경
  next/src/components/video-chat/ChatSection/ChatList/index.tsx
  next/src/components/video-chat/ChatSection/ChatList/style.tsx
Labels: feature, frontend

#364 feat: 이미지 업로드 프런트측 기능 작성 (mock api 사용)
  next/src/components/video-chat/ChatSection/InputBox/TuiEditor.tsx
  next/src/components/video-chat/ChatSection/InputBox/TuiEditorWrapper.tsx
  next/src/lib/apis.ts
  next/src/pages/api/chat/upload/index.ts
  next/typings/chat.ts
Labels: feature, frontend

#367 refactor: 채팅 입력창 컴포넌트 리팩터링, 드래그 앤 드롭 기능 뼈대 작성
  next/package-lock.json
  next/package.json
  next/src/components/common/SVGButton/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/ChatContext.tsx
  next/src/components/video-chat/ChatSection/InputBox/Editor/TuiEditor.tsx
  next/src/components/video-chat/ChatSection/InputBox/Editor/TuiEditorWrapper.tsx
  next/src/components/video-chat/ChatSection/InputBox/Editor/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/Editor/style.tsx
  next/src/components/video-chat/ChatSection/InputBox/Header/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/Header/style.tsx
  next/src/components/video-chat/ChatSection/InputBox/TextArea/ImageUploadableTextArea.tsx
  next/src/components/video-chat/ChatSection/InputBox/TextArea/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/TextArea/style.tsx
  next/src/components/video-chat/ChatSection/InputBox/TextArea/useCustomDropzone.tsx
  next/src/components/video-chat/ChatSection/InputBox/colourableLanguages.ts
  next/src/components/video-chat/ChatSection/InputBox/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/style.tsx
  next/src/pages/video-chat/[id].tsx
Labels: feature, refactor, frontend

#369 !HOTFIX: 누락된 스타일 파일 추가
  next/src/components/common/SVGButton/index.tsx
  next/src/components/common/SVGButton/style.tsx
Labels: fix, frontend

#370 feat: 에디터 안킨 상태에서 드래그 앤 드롭으로 이미지 추가할 수 있는 기능 추가
  next/src/components/video-chat/ChatSection/ChatContext.tsx
  next/src/components/video-chat/ChatSection/ChatList/index.tsx
  next/src/components/video-chat/ChatSection/Container/index.tsx
  next/src/components/video-chat/ChatSection/Container/style.tsx
  next/src/components/video-chat/ChatSection/Container/useDropzone.tsx
  next/src/components/video-chat/ChatSection/InputBox/Editor/EditorWrapper.tsx
  next/src/components/video-chat/ChatSection/InputBox/Editor/TuiEditor.tsx
  next/src/components/video-chat/ChatSection/InputBox/Editor/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/Editor/style.tsx
  next/src/components/video-chat/ChatSection/InputBox/TextArea/ImageUploadableTextArea.tsx
  next/src/components/video-chat/ChatSection/InputBox/TextArea/index.tsx
  next/src/components/video-chat/ChatSection/InputBox/TextArea/style.tsx
  next/src/components/video-chat/ChatSection/InputBox/TextArea/useCustomDropzone.tsx
  next/src/components/video-chat/ChatSection/index.tsx
  next/src/components/video-chat/Sidebar/index.tsx
  next/src/pages/video-chat/[id].tsx
Labels: feature, refactor, frontend

#371 feat: FileChat 삭제
  next/src/components/video-chat/ChatSection/Chat/FileChat.tsx
  next/src/components/video-chat/ChatSection/Chat/Message.tsx
  next/src/components/video-chat/ChatSection/Chat/index.tsx
  next/src/components/video-chat/ChatSection/Chat/style.tsx
  next/typings/chat.ts
Labels: help wanted, feature, frontend, backend

#372 feat: 채팅 announcement 스타일 추가 작업
  next/src/components/video-chat/ChatSection/Chat/Announcement.tsx
  next/src/components/video-chat/ChatSection/Chat/style.tsx
Labels: feature, frontend

#375 feat: ci 레디스 서버 추가
  .github/workflows/node.js.yml
Labels: feature, backend
