Repository bear-bear-bear/mogakco, pull requests merged in 2021-05, with the labels that each got.

#54 feature: 인증 컨트롤러 JSDoc 업데이트
  controllers/auth.controller.ts
Labels: enhancement

#55 feature: 이메일 기능 개선
  .env.example
  controllers/auth.controller.ts
  lib/backend/log.ts
  modules/mail.module.ts
Labels: enhancement

#56 설정: CI 에 MariaDB 설정 추가 및 환경 설정 주입 ( risk high )
  .env.example
  .github/workflows/node.js.yml
Labels: risk

#60 feature: ScrollTop 기능을 가진 컴포넌트를 작성하고 랜딩 페이지에 추가
  components/common/ScrollTop/index.js
  components/common/ScrollTop/style.js
  components/globalStyles/_Variables.js
  lib/scrollToTop.js
  pages/index.js
Labels: enhancement

#58 feature: 로그인한 유저에 대한 액션, 리듀서, 셀렉터 작성
  components/landing/ContentBlock/LeftContentBlock/index.js
  components/landing/Header/index.js
  redux/actions/common/user.js
  redux/reducers/common/user.js
  redux/reducers/index.js
  redux/selectors/common/user.js
Labels: feature

#64 refactor: redux-tookit 적용, 해당 모듈 사용하여 기존 코드 리팩토링
  components/SignUp/Auth/index.js
  components/SignUp/Info/index.js
  components/SignUp/Interest/index.js
  lib/fromActionTypes.js
  package-lock.json
  package.json
  redux/actions/common/user.js
  redux/actions/signup/auth.js
  redux/actions/signup/info.js
  redux/actions/signup/interest.js
  redux/actions/signup/signup.js
  redux/reducers/common/user.js
  redux/reducers/index.js
  redux/reducers/signup/index.js
  redux/sagas/signup/auth.js
  redux/sagas/signup/info.js
  redux/sagas/signup/interest.js
  redux/sagas/signup/signup.js
  redux/selectors/common/user.js
  redux/selectors/signup/index.js
Labels: refactor

#65 수정: 회원가입 이메일 인증 오류 해결
  controllers/auth.controller.ts
  modules/mail.module.ts
  services/email.service.ts
Labels: backend, bug

#67 fix: 해결 못한 네이밍 컨벤션 문제 수정
  components/SignUp/Auth/index.js
  components/landing/ContentBlock/LeftContentBlock/index.js
  components/landing/Header/index.js
  pages/signup.js
  redux/reducers/index.js
  redux/sagas/index.js
  redux/sagas/signup/auth.js
  redux/sagas/signup/index.js
  redux/sagas/signup/info.js
  redux/sagas/signup/interest.js
  redux/sagas/signup/signup.js
Labels: fix, frontend

#59 feature: 프런트엔드 렌더링 테스트 케이스 작성안
  .eslintrc.js
  .github/workflows/node.js.yml
  jest.config.ts
  lib/svgTransform.js
  models/repositories/user.repository.ts
  package-lock.json
  package.json
  services/user.service.ts
  test/unit/frontend/components/TestRenderer.jsx
  test/unit/frontend/pages/TestRenderer.spec.jsx
  test/unit/frontend/test-config.json
  test/unit/helper/userMockRepository.ts
  test/unit/server/services/dto/update-user-request.dto.ts
  test/unit/server/services/user.test.ts
  test/unit/server/test-config.json
Labels: feature, frontend, test

#68 기능: alias 설정 보완, 타입 스크립트 라이브러리 설치
  .babelrc
  next.config.js
  package-lock.json
  package.json
  tsconfig.json
Labels: frontend

#72 기능: 이메일 검증 Api 작성 및 기존 코드 리팩터링
  controllers/auth.controller.ts
  lib/backend/log.ts
  models/entities/user.verify.ts
  models/repositories/user.repository.ts
  services/email.service.ts
  services/email/user-verify.pug
  services/user.service.ts
Labels: backend, fix

#73 feat: signup 페이지 UI/UX 개선 및 잔버그 수정
  components/SignUp/Auth/index.js
  components/SignUp/Complete/index.js
  components/SignUp/Header/index.js
  components/SignUp/Header/style.js
  components/SignUp/Info/style.js
  components/SignUp/common/styles.js
  components/common/Button/style.js
  components/landing/Container/style.js
  components/landing/ContentBlock/LeftContentBlock/index.js
  components/landing/ContentBlock/LeftContentBlock/style.js
  components/landing/Header/style.js
  components/landing/MiddleBlock/index.js
  components/signup/Auth/index.js
  components/signup/Auth/style.js
  components/signup/Complete/index.js
  components/signup/Complete/style.js
  components/signup/Header/index.js
  components/signup/Header/style.js
  components/signup/Info/index.js
  components/signup/Info/style.js
  components/signup/Interest/index.js
  components/signup/Interest/style.js
  components/signup/ProgressBar/index.js
  components/signup/ProgressBar/style.js
  components/signup/common/styles.js
  pages/index.js
  pages/signup.js
  redux/reducers/index.js
  redux/reducers/landing/index.js
  redux/reducers/signup/index.js
  redux/sagas/signup/auth.js
  redux/selectors/landing/index.js
  redux/selectors/signup/index.js
Labels: feature, frontend

#74 fix: 백엔드 코드 리팩터링 및 코드 어시스트 수정
  controllers/auth.controller.ts
  models/repositories/user.repository.ts
  models/repositories/user.verify.repository.ts
  services/auth.service.ts
  services/email.service.ts
  services/user.service.ts
Labels: backend, feature, fix, refactor

#75 기능: 이메일 검증 api 작성
  controllers/auth.controller.ts
  services/user.service.ts
Labels: backend, feature, refactor

#76 refactor: 사용하지 않는 signup 페이지 saga 삭제, state name 의미에 맞게 변경
  components/signup/Auth/index.js
  components/signup/Info/index.js
  components/signup/Interest/index.js
  pages/signup.js
  redux/reducers/signup/index.js
  redux/sagas/index.js
  redux/sagas/signup/auth.js
  redux/sagas/signup/index.js
  redux/sagas/signup/info.js
  redux/sagas/signup/interest.js
  redux/sagas/signup/signup.js
  redux/selectors/signup/index.js
Labels: frontend, refactor

#77 기능: 프런트엔드 axios 관련 편의성 라이브러리 작성
  lib/apiClient.js
  next.config.js
  package-lock.json
  package.json
  redux/sagas/common/user.js
  redux/sagas/index.js
  redux/sagas/signup/index.js
Labels: feature, frontend

#80 fix: ci path 수정
  .github/workflows/node.js.yml
  nest/package.json
  nest/test/unit/services/dto/update-user-request.dto.ts
  nest/test/unit/services/user.test.ts
  nest/test/unit/test-config.json
  next/lib/regex.js
Labels: devops, fix

#81 기능: 백엔드 마이그레이션 추가 및 CI 데이터베이스 업데이트
  .env.example
  .github/workflows/node.js.yml
  .gitignore
  nest/migrations/1622256071819-user.ts
  nest/models/entities/user.ts
  nest/modules/app.module.ts
  nest/package-lock.json
  nest/package.json
  package-lock.json
Labels: backend, devops, feature

#82 feat: 프론트 백 환경 분리 누락사항 수정
  nest/.gitignore
  nest/controllers/auth.controller.ts
  nest/dist/controllers/auth.controller.js
  nest/dist/controllers/auth.controller.js.map
  nest/dist/jest.config.js
  nest/dist/jest.config.js.map
  nest/dist/libs/log.js.map
  nest/dist/libs/makeHash.js.map
  nest/dist/libs/types/index.js.map
  nest/dist/services/email.service.js
  nest/dist/services/email.service.js.map
  nest/dist/services/user.service.js
  nest/dist/services/user.service.js.map
  nest/dist/tsconfig.build.tsbuildinfo
  nest/jest.config.ts
  nest/lib/log.ts
  nest/lib/makeHash.ts
  nest/lib/types/index.ts
  nest/package-lock.json
  nest/package.json
  nest/services/email.service.ts
  nest/services/user.service.ts
  nest/tsconfig.json
  next/components/common/ScrollTop/index.js
  next/components/signup/Auth/index.js
  next/components/signup/Info/index.js
  next/package-lock.json
  next/package.json
  next/redux/reducers/signup/index.js
Labels: devops, feature, fix

#85 fix: 오류 발생하는 nest/migration 디렉터리 삭제
  nest/migrations/1622256071819-user.ts
  nest/package-lock.json
Labels: backend, fix

#87 feat: 컴포넌트 재사용성 작업
  next/components/common/AuthContainer/index.js
  next/components/common/AuthContainer/style.js
  next/components/common/Checkbox/index.js
  next/components/common/Checkbox/style.js
  next/components/common/Desc/index.js
  next/components/common/Desc/style.js
  next/components/common/Form/index.js
  next/components/common/Form/style.js
  next/components/common/InputBox/index.js
  next/components/common/InputBox/style.js
  next/components/common/InputWrapper/index.js
  next/components/common/InputWrapper/style.js
  next/components/common/Label/index.js
  next/components/common/Label/style.js
  next/components/common/Warning/index.js
  next/components/common/Warning/style.js
  next/components/signup/Auth/index.js
  next/components/signup/Auth/style.js
  next/components/signup/Complete/index.js
  next/components/signup/Header/index.js
  next/components/signup/Header/style.js
  next/components/signup/Info/index.js
  next/components/signup/Info/style.js
  next/components/signup/Interest/index.js
  next/components/signup/Interest/style.js
  next/components/signup/ProgressBar/index.js
  next/components/signup/common/styles.js
  next/pages/signup.js
  next/redux/reducers/signup/index.js
Labels: feature, frontend, refactor

#88 feat: signup페이지에 customHead 적용, page props위치를 컴포넌트 내부에서 외부로 변경
  next/pages/index.js
  next/pages/signup.js
Labels: feature, frontend, refactor

#90 feature: cors 허용 옵션 작성
  nest/main.ts
Labels: backend, feature

#92 백엔드: eslint 에러 수정
  .github/workflows/node.js.yml
  nest/.eslintrc.json
  nest/.prettierrc
  nest/controllers/auth.controller.ts
  nest/controllers/dto/response.ts
  nest/controllers/exception/login.exception.ts
  nest/lib/log.ts
  nest/lib/makeHash.ts
  nest/lib/types/index.ts
  nest/models/dto/create-user.dto.ts
  nest/models/dto/login-user.dto.ts
  nest/models/entities/user-verify.entity.ts
  nest/models/entities/user.entity.ts
  nest/models/repositories/user.repository.ts
  nest/models/repositories/user.verify.repository.ts
  nest/modules/app.module.ts
  nest/package-lock.json
  nest/package.json
  nest/services/auth.service.ts
  nest/services/email/user-verify.pug
  nest/services/passport/jwt.refresh.strategy.ts
  nest/services/user.service.ts
  nest/test/helper/userMockRepository.ts
  nest/test/unit/services/dto/update-user-request.dto.ts
  nest/test/unit/services/user.test.ts
Labels: backend, devops, fix

#93 fix: .env.example path 변경
  .github/workflows/node.js.yml
  nest/.env.example
Labels: devops, fix

#96 fix: 이메일 검증 api 항상 false 리턴하는 오류 수정
  nest/controllers/auth.controller.ts
Labels: backend, fix

#97 fix: 오타 수정
  nest/controllers/auth.controller.ts
Labels: backend, fix

#103 feature: field 항목 데이터 모델링
  nest/models/entities/user-field.entity.ts
  nest/models/entities/user-verify.entity.ts
  nest/models/entities/user.entity.ts
Labels: backend, feature

#104 feature: 목적 구분을 위한 컨트롤러 분리
  nest/controllers/auth.controller.ts
  nest/controllers/user.controller.ts
  nest/modules/user.module.ts
  nest/services/auth.service.ts
  nest/services/email/user-verify.pug
  nest/services/passport/jwt.refresh.strategy.ts
  nest/services/user.service.ts
Labels: backend

#106 기능: 희망 분야 목록 불러오기 Api 작성
  nest/controllers/user.controller.ts
  nest/modules/user.module.ts
  nest/services/user.service.ts
  nest/test/unit/user/index.test.ts
Labels: backend, feature

#110 백엔드: 직업 모델링과 리스트 불러오기 Api
  nest/controllers/user.controller.ts
  nest/models/entities/users-job.entity.ts
  nest/services/user.service.ts
Labels: backend, feature

#111 feat: 회원가입 API 연동, 프론트 기능 개발
  next/components/common/Label/style.js
  next/components/signup/Auth/index.js
  next/components/signup/Complete/index.js
  next/components/signup/Info/index.js
  next/components/signup/Info/style.js
  next/components/signup/Interest/index.js
  next/components/signup/Interest/style.js
  next/lib/apiClient.js
  next/lib/regex.js
  next/package-lock.json
  next/package.json
  next/redux/reducers/common/user.js
  next/redux/reducers/landing/index.js
  next/redux/reducers/signup/index.js
  next/redux/sagas/signup/index.js
  next/redux/selectors/signup/index.js
Labels: feature, frontend, risk

#116 fix: 서버 측 API 변경에 따라 API url 변경 및 적용
  next/lib/APIs.js
  next/redux/reducers/signup/index.js
  next/redux/sagas/common/user.js
  next/redux/sagas/signup/index.js
Labels: feature, fix, frontend
